POST http://localhost:3000/auth/register
Content-Type: application/json

{
"fullName" : "fiiwe barry",
"email" : "ikpaprecious2@gmail.com",
"password" : "12345"
}


###

POST http://localhost:3000/auth/login   
Content-Type: application/json

{
"email" : "ikpaprecious2@gmail.com",
"password" : "12345"
}