POST http://localhost:3000/auth/register

Content-Type: application/json
{
"fullName" : "fiiwe barry",
"email" : "fiiwebarry@gmail.com",
"password" : "fiiwebarry"
}


###

# POST http://localhost:3000/auth/register
   
# Content-Type: application/json
# {
# "fullName" : "fiiwe barisanem",
# "email" : "fiiwebarry@yahoo.com",
# "password" : "barryfiiwe"
# }